// Replit Static File Server
// Serves the static site and injects config.js from environment variables.

const http = require('http');
const fs = require('fs');
const path = require('path');
const PORT = parseInt(process.env.PORT || '5000', 10);

// Build the CONFIG object from environment variables (same keys as generate-config.js)
const config = {
  SUPABASE_URL:      process.env.SUPABASE_URL      || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  SITE_URL:          (process.env.SITE_URL || '').replace(/\/$/, ''),
  IMAGEKIT_URL:      process.env.IMAGEKIT_URL        || '',
  IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY || '',
  GEOAPIFY_API_KEY:  process.env.GEOAPIFY_API_KEY   || '',
  COMPANY_NAME:      process.env.COMPANY_NAME        || '',
  COMPANY_EMAIL:     process.env.COMPANY_EMAIL       || '',
  COMPANY_PHONE:     process.env.COMPANY_PHONE       || '',
  COMPANY_TAGLINE:   process.env.COMPANY_TAGLINE     || '',
  COMPANY_ADDRESS:   process.env.COMPANY_ADDRESS     || '',
  LEASE_DEFAULT_LATE_FEE_FLAT:  Number(process.env.LEASE_DEFAULT_LATE_FEE_FLAT)  || 50,
  LEASE_DEFAULT_LATE_FEE_DAILY: Number(process.env.LEASE_DEFAULT_LATE_FEE_DAILY) || 10,
  LEASE_DEFAULT_EXPIRY_DAYS:    Number(process.env.LEASE_DEFAULT_EXPIRY_DAYS)    || 7,
  FEATURES: {
    CO_APPLICANT:     process.env.FEATURE_CO_APPLICANT     !== 'false',
    VEHICLE_INFO:     process.env.FEATURE_VEHICLE_INFO     !== 'false',
    DOCUMENT_UPLOAD:  process.env.FEATURE_DOCUMENT_UPLOAD  !== 'false',
    MESSAGING:        process.env.FEATURE_MESSAGING        !== 'false',
    REALTIME_UPDATES: process.env.FEATURE_REALTIME_UPDATES !== 'false',
  },
};

// Generate the config.js content (mirrors what generate-config.js produces)
const configJs = `// Auto-generated by server.js — do not edit directly
const CONFIG = ${JSON.stringify(config, null, 2)};

// Image helper used by property cards
CONFIG.img = function(url, tr) {
  if (!url || !CONFIG.IMAGEKIT_URL) return url || '';
  const base = CONFIG.IMAGEKIT_URL.replace(/\\/$/, '');
  const transforms = {
    card: 'tr:w-600,h-400,c-at_max,q-80,f-webp',
    card_2x: 'tr:w-1200,h-800,c-at_max,q-80,f-webp',
    thumb: 'tr:w-200,h-150,c-at_max,q-70,f-webp',
    full: 'tr:w-1400,q-85,f-webp',
  };
  const t = transforms[tr] || '';
  return t ? base + '/' + t + url : base + url;
};

CONFIG.srcset = function(url, tr1, tr2) {
  return CONFIG.img(url, tr1) + ' 1x, ' + CONFIG.img(url, tr2) + ' 2x';
};
`;

// MIME types for static file serving
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico':  'image/x-icon',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
  '.txt':  'text/plain; charset=utf-8',
  '.xml':  'application/xml; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
  '.zip':  'application/zip',
};

const ROOT = __dirname;

function serveFile(res, filePath, statusCode) {
  const ext = path.extname(filePath).toLowerCase();
  const mime = MIME[ext] || 'application/octet-stream';
  try {
    const data = fs.readFileSync(filePath);
    res.writeHead(statusCode || 200, { 'Content-Type': mime });
    res.end(data);
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/html' });
    res.end(fs.existsSync(path.join(ROOT, '404.html'))
      ? fs.readFileSync(path.join(ROOT, '404.html'))
      : '<h1>404 Not Found</h1>');
  }
}

const server = http.createServer((req, res) => {
  let urlPath = req.url.split('?')[0];

  // Redirect /favicon.ico to the SVG favicon (browsers always auto-request this)
  if (urlPath === '/favicon.ico') {
    res.writeHead(302, { Location: '/assets/favicon.svg' });
    return res.end();
  }

  // Health check — shows which env vars are set/missing (no secret values exposed)
  if (urlPath === '/health') {
    const checks = {
      SUPABASE_URL:        !!process.env.SUPABASE_URL,
      SUPABASE_ANON_KEY:   !!process.env.SUPABASE_ANON_KEY,
      IMAGEKIT_URL:        !!process.env.IMAGEKIT_URL,
      IMAGEKIT_PUBLIC_KEY: !!process.env.IMAGEKIT_PUBLIC_KEY,
      GEOAPIFY_API_KEY:    !!process.env.GEOAPIFY_API_KEY,
      COMPANY_NAME:        !!process.env.COMPANY_NAME,
      SITE_URL:            !!process.env.SITE_URL,
    };
    const missing = Object.entries(checks).filter(([,v]) => !v).map(([k]) => k);
    const status = missing.length === 0 ? 'ok' : 'degraded';
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ status, checks, missing }, null, 2));
  }

  // Serve dynamically generated config.js
  if (urlPath === '/config.js') {
    res.writeHead(200, {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'no-store',
    });
    return res.end(configJs);
  }

  // Resolve file path
  let filePath = path.join(ROOT, urlPath);

  // Security: prevent path traversal outside ROOT
  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403);
    return res.end('Forbidden');
  }

  // If the path is a directory, look for index.html inside it
  if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
    filePath = path.join(filePath, 'index.html');
  }

  // If no extension and no file found, try appending .html
  if (!fs.existsSync(filePath) && !path.extname(urlPath)) {
    const withHtml = filePath + '.html';
    if (fs.existsSync(withHtml)) {
      filePath = withHtml;
    }
  }

  if (!fs.existsSync(filePath)) {
    const notFound = path.join(ROOT, '404.html');
    res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
    return res.end(fs.existsSync(notFound) ? fs.readFileSync(notFound) : '<h1>404 Not Found</h1>');
  }

  serveFile(res, filePath);
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on port ${PORT}`);
  console.log(`SUPABASE_URL: ${config.SUPABASE_URL ? '✓ set' : '✗ missing'}`);
  console.log(`SUPABASE_ANON_KEY: ${config.SUPABASE_ANON_KEY ? '✓ set' : '✗ missing'}`);
  console.log(`IMAGEKIT_URL: ${config.IMAGEKIT_URL ? '✓ set' : '✗ missing'}`);
  console.log(`GEOAPIFY_API_KEY: ${config.GEOAPIFY_API_KEY ? '✓ set' : '✗ missing'}`);
});
